### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/wesleyelliott/kubwa/rule/Rule 

### ISSUE THREAD

**Issue by rahul860366** [WesleyElliott/Kubwa#10]
I am getting this error: Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.wesleyelliott.kubwa.KubwaCompiler could not be instantiated: java.lang.NoClassDefFoundError: com/wesleyelliott/kubwa/rule/Rule

**Comment by WesleyElliott** [comment]
Can you post your gradle file?

**Comment by RootSoft** [comment]
I'm having the exact same issue and it seems a lot of other users are having the same issue.

> error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.wesleyelliott.kubwa.KubwaCompiler could not be instantiated: java.lang.NoClassDefFoundError: com/wesleyelliott/kubwa/rule/Rule

I was working on version 1.0.1 and wanted to add an extra Regex validation rule to my class.
I can't post my entire build.gradle so here are some extracts:

`
dataBinding {
        enabled = true
    }

    dexOptions {
        jumboMode = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

ext {
    retrofitVersion = '2.3.0'
    okhttpVersion = '3.9.1'
    gsonVersion = '2.8.2'
    daggerVersion = '2.13'
    playServicesVersion = '15.0.0'
    supportLibraryVersion = '27.1.1'
    icepickVersion = '3.2.0'
    facebookVersion = '4.30.0'
    mapboxVersion = '5.5.0'
}

//Dagger
    annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    implementation "com.google.dagger:dagger:$daggerVersion"
    runtimeOnly 'javax.annotation:jsr250-api:1.0'

//Icepick for savedInstanceStates
    implementation "frankiesardo:icepick:$icepickVersion"
    annotationProcessor "frankiesardo:icepick-processor:$icepickVersion"

//Validation
    implementation 'com.wesleyelliott:kubwa-annotations:1.1.1', {
        exclude group: 'com.google.android'
    }
    annotationProcessor 'com.wesleyelliott:kubwa-compiler:1.1.1'`

**Comment by WesleyElliott** [comment]
Thanks - I've found the issue, and hopefully pushed a working version. Please try with 1.1.3 and let me know

**Comment by RootSoft** [comment]
I just tried it by adding the following above my ViewModel:
`@Regex(errorMessage = R.string.signup_password_not_complex, regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,64}$")`

> java.lang.NoSuchMethodException: com.wesleyelliott.kubwa.rule.RegexRule.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.wesleyelliott.kubwa.KubwaCompiler.createRule(KubwaCompiler.java:357)
	at com.wesleyelliott.kubwa.KubwaCompiler.parse(KubwaCompiler.java:210)
	at com.wesleyelliott.kubwa.KubwaCompiler.parseRegex(KubwaCompiler.java:267)
	at com.wesleyelliott.kubwa.KubwaCompiler.parseSingle(KubwaCompiler.java:279)
	at com.wesleyelliott.kubwa.KubwaCompiler.processTargets(KubwaCompiler.java:161)
	at com.wesleyelliott.kubwa.KubwaCompiler.process(KubwaCompiler.java:137)

Resulting in a package be.xxx.databinding does not exist

**Comment by WesleyElliott** [comment]
@RootSoft  - thanks for the info. I've pushed an update to address that (see 1.2.0). I'm closing this issue as its fixed. If you run into any more, please open a new issue.
